services:
  ledger-service:
    build: ./ledger-service
    ports:
      - "8081:8081"

  transfer-service:
    build: ./transfer-service
    ports:
      - "8080:8080"
    depends_on:
      - ledger-service
    environment:
      - LEDGER_SERVICE_URL=http://ledger-service:8081